language: ruby
rvm:
  - 2.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script:
  - npm install;
  - bundle exec jekyll serve --no-watch --detach;
  - sleep 3;

script:
  - node_modules/intern/bin/intern-runner.js config=tests/intern/intern;
  - bundle exec htmlproof ./_site --disable-external;
