addons:
  hosts:
    - sochadev.com

language: ruby
rvm:
  - 2.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
    - node_modules

before_script:
  # Start X Virtual Framebuffer (needed for headless GUI).
  - sh -e /etc/init.d/xvfb start;
  - export DISPLAY=:99.0;

  # Download and start Selenium standalone server; note the silencer.
  - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar;
  - java -jar selenium-server-standalone-2.48.2.jar &> /dev/null &
  - sleep 3;

  # Serve Jekyll site at http://127.0.0.1:4000. Note tests/config/main.js mirror of same.
  - bundle exec jekyll serve --host 127.0.0.1 --port 4000 --no-watch --detach;
  - sleep 3;

  # Install node_modules.
  - npm install;

script:
  # Run Intern.js tests.
  - node_modules/intern/bin/intern-runner.js config=tests/intern/intern environment=ci;
  # Run HTML proofer tests.
  - bundle exec htmlproof ./_site --disable-external;
