language: ruby
rvm:
- 2.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script:
  - npm install;
  - _site/chromedriver --port=4444 --url-base=wd/hub;
  - sleep 3;

script: ./script/cibuild

