addons:
  hosts:
    - sochadev.com

language: ruby
rvm:
  - 2.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
    - node_modules

before_script:
  # Upgrade nodejs itself. Many of our modules are unhappy with the default on
  # Travis - seems to be 0.10.x
  - nvm install 0.12;
  - node -v;
  
  # Install node_modules.
  - npm install;
  
  # Start X Virtual Framebuffer (needed for headless GUI).
  # Use alternate start method to allow explicitly setting "screen" dimensions.
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#sts=Using%20xvfb%20to%20Run%20Tests%20That%20Require%20a%20GUI
  - export DISPLAY=:99.0;
  # - sh -e /etc/init.d/xvfb start;
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16;
  - sleep 3;

  # Download and start Selenium standalone server; note the silencer.
  - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar;
  - java -jar selenium-server-standalone-2.48.2.jar &> /dev/null &
  - sleep 3;

  # Serve Jekyll site at http://127.0.0.1:4000. Note tests/config/main.js mirror of same.
  - bundle exec jekyll serve --host 127.0.0.1 --port 4000 --no-watch --detach;
  - sleep 3;

script:
  # Run Intern.js tests.
  - mkdir -p tests/intern/screenshots;
  - node_modules/intern/bin/intern-runner.js config=tests/intern/intern environment=ci;
  # Run HTML proofer tests.
  - bundle exec htmlproof ./_site --disable-external;
