# Site settings.
baseurl: http://sochadev.github.io
title: Socha Dev
tagline: development overflow, triage and problem solving
logoUrl: https://avatars2.githubusercontent.com/u/1489168?v=3&s=36
description: Socha Dev is a white-label web and app development shop built to help your team succeed. We specialize in overflow, triage and problem solving services.
author: jeffeoff, natemow
rest_api: http://wintermute.sochadev.com/api-www
ga_code: UA-45204620-1
defaults:
  -
    scope:
      pages: "" # Denotes all pages.
      type: "pages"
    values:
      layout: default
  -
    scope:
      pages: "" # Denotes all pages.
      type: "posts"
    values:
      layout: default
  -
    scope:
      pages: "" # Denotes all pages.
      type: "drafts"
    values:
      layout: default

# Handling reading.
exclude: [ nbproject, vendor, script, assets/sass, assets/images/sprites/, Gemfile, Gemfile.lock, gulpfile.js, package.json, node_modules, README.md ]

# Conversion.
markdown: kramdown
permalink: pretty

