# Site settings.
# baseurl: http://sochadev.com
port: 4000
baseurl: http://sochadev.com
title: Socha Dev
tagline: development overflow, triage and problem solving
description: Socha Dev is a white-label web and app development shop built to help your team succeed. We specialize in overflow, triage and problem solving services.
author: Socha Dev
prodBuild: false
logoUrl: /assets/images/socha-dev.png
githubUrl: https://github.com/SochaDev
drupalUrl: https://www.drupal.org/node/2439991
restApiUrl: http://api.sochadev.com

contact:
  email: socha dot jason at sochadev dot com
  phone: 608-213-9838

google:
  analyticsCode: UA-45204620-1
facebook:
  appId: 1657090981233155

defaults:
  -
    scope:
      pages: "" # Denotes all pages.
      type: "pages"
    values:
      layout: default
  -
    scope:
      pages: "" # Denotes all pages.
      type: "posts"
    values:
      layout: default
  -
    scope:
      pages: "" # Denotes all pages.
      type: "drafts"
    values:
      layout: default

# Handling reading.
exclude: [
  nbproject,
  vendor,
  script,
  assets/sass,
  assets/images/sprites/,
  Gemfile, Gemfile.lock,
  gulpfile.js, package.json, node_modules, tests, npm-debug.log,
  README.md,
  .travis.yml
]

# Conversion.
markdown: kramdown
permalink: pretty

