# Site settings.
baseurl: http://sochadev.com
title: Socha Dev
description: Socha Dev is a web development team built to help your company succeed. We specialize in overflow, triage and problem solving services.
author: jeffeoff, natemow
ga_code: UA-66386274-1
defaults:
  -
    scope:
      pages: "" # Denotes all pages.
      type: "pages"
    values:
      layout: default
  -
    scope:
      pages: "" # Denotes all pages.
      type: "posts"
    values:
      layout: default
  -
    scope:
      pages: "" # Denotes all pages.
      type: "drafts"
    values:
      layout: default

# Handling reading.
exclude: [ nbproject, vendor, script, assets/sass, assets/images/sprites/, Gemfile, Gemfile.lock, gulpfile.js, package.json, node_modules, README.md ]

# Conversion.
markdown: kramdown
permalink: pretty

