#!/usr/bin/env bash

# Halt script on error.
set -e;

# Build the Jekyll site and run the HTML proofer.
bundle exec jekyll build;
# bundle exec htmlproof ./_site --disable-external --file_ignore "node_modules/*";

# Run Intern.js tests.
cd ./_site && ls -lah;
./chromedriver --port=4444 --url-base=wd/hub > /dev/null &
./node_modules/intern/bin/intern-runner.js config=tests/intern/intern;
